name: test if

on: pull_request_review

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: branch name if
        if: github.head_ref == 'develop'
        run: echo hello
        
      - name: test
        run: echo ${github.event.pull_request.head.ref}

      - name: Print branch name
        env:
          BRANCH_NAME: ${{github.head_ref}}
        run: echo $BRANCH_NAME

      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Print branch name
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: echo $BRANCH_NAME
