name: test if

on: pull_request_review

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: branch name if
        if: github.event.pull_request.head.ref == 'develop'
        run: echo hello

      - name: Print branch name
        env:
          BRANCH_NAME: ${{github.event.pull_request.head.ref}}
        run: echo $BRANCH_NAME
        
      - name: Print branch name
        env:
          BRANCH_NAME: ${{github.event.pull_request_review.head.ref}}
        run: echo $BRANCH_NAME
        
      - name: dump context
        run: echo '${{ toJSON(github) }}'
